version: '3'
services:
  wordpress:
    image: wordpress:latest
    container_name: pj10_wordpress
    volumes:
      - ./source:/var/www/html
      - ./source/backup:/tmp/backup
      - ./source/log:/tmp/log
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    networks:
      - pj10_network
    env_file: .env
  db:
    image: mysql:5.7
    container_name: pj10_mysql
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - pj10_network
    env_file: .env
volumes:
  db-data:
networks:
  pj10_network: